### PR TITLE
Add commons controller

### PR DESCRIPTION
**Pull request by pconrad**
This PR contains a first attempt at a controller for the Commons.

One issue is that the POST request doesn't work unless you disable CSRF protection, which seems like a bad idea for the long term. I suggest, however, that rather than letting that be a blocker, we temporarily disable CSRF protection so that the team can make progress, while we tackle that as a separate concern.

Let's discuss as a team.

The intent is to add  these endpoints:

* GET `/api/commons` : list all commons
* POST `/api/commons` : add a new commons
* DELETE `/api/commons/{id}` : delete a commons

Another issue is that the form for a commons on the current app looks like this:

image

But of the fields in this form, the database table for a Commons only has a place to store the commons name.   This raises the question: where are the other fields? (Cow price, milk price, start date, end date?)

### CODE REVIEW

**Comment by pconrad** [comment]
One concern here is the use of `@Transactional` which some authors say is an anti-pattern.

If we don't put it on the `CurrentUserServiceImpl` class, then when we try to get the current user, we get the `500` error below.   The problem seems to be that since the User model has a OneToMany relationship with the Commons table, the user needs to do a query to get all of that information.

Unfortunately, the database connection is already closed.  Putting @Transactional on the service class is a heavy handed workaround that fixes the problem.  But I wonder if there is a better way.

```
{
  "timestamp": "2021-05-06T22:33:48.322+00:00",
  "status": 500,
  "error": "Internal Server Error",
  "trace": "org.springframework.http.converter.HttpMessageNotWritableException: Could not write JSON: failed to lazily initialize a collection of role: edu.ucsb.cs156.happiercows.entities.User.commons, could not initialize proxy - no Session; nested exception is com.fasterxml.jackson.databind.JsonMappingException: failed to lazily initialize a collection of role: edu.ucsb.cs156.happiercows.entities.User.commons, could not initialize proxy - no Session (through reference chain: edu.ucsb.cs156.happiercows.models.CurrentUser[\"user\"]->edu.ucsb.cs156.happiercows.entities.User[\"commons\"])\n\tat org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.writeInternal(AbstractJackson2HttpMessageConverter.java:461)\n\tat 
...
com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:755)\n\t... 98 more\n",
  "message": "Could not write JSON: failed to lazily initialize a collection of role: edu.ucsb.cs156.happiercows.entities.User.commons, could not initialize proxy - no Session; nested exception is com.fasterxml.jackson.databind.JsonMappingException: failed to lazily initialize a collection of role: edu.ucsb.cs156.happiercows.entities.User.commons, could not initialize proxy - no Session (through reference chain: edu.ucsb.cs156.happiercows.models.CurrentUser[\"user\"]->edu.ucsb.cs156.happiercows.entities.User[\"commons\"])",
  "path": "/api/currentUser"
}
```

**Comment by pconrad** [comment]
Some possibly useful info: https://www.baeldung.com/transaction-configuration-with-jpa-and-spring#the-transactional-annotation

**Comment by pconrad** [comment]
Here's a SO article on the original problem to which `@Transactional` was a possible (but also considered harmful) solution:

https://stackoverflow.com/questions/11746499/how-to-solve-the-failed-to-lazily-initialize-a-collection-of-role-hibernate-ex

**Comment by pconrad** [comment]
It has to do with EAGER loading vs LAZY loading:

https://stackoverflow.com/questions/2990799/difference-between-fetchtype-lazy-and-eager-in-java-persistence-api

**Comment by pconrad** [comment]
https://www.baeldung.com/hibernate-lazy-eager-loading

**Review by sethvanb — APPROVED** [review]
LGTM

**Review by kevbbn — APPROVED** [review]
lgtm

**Review by AnikaArora — COMMENTED** [review]
lgtm

**Review by AnikaArora — APPROVED** [review]
lgtm!

**Pull request merged**
